"""empty message

Revision ID: 10ff652bd77e
Revises: 1d26e318a800
Create Date: 2019-04-02 22:19:45.369311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ff652bd77e'
down_revision = '1d26e318a800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisine',
    sa.Column('cuisine_id', sa.Integer(), nullable=False),
    sa.Column('cuisine_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cuisine_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuisine')
    # ### end Alembic commands ###
