"""empty message

Revision ID: 1d26e318a800
Revises: 
Create Date: 2019-04-02 22:03:56.510085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d26e318a800'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=80), nullable=True),
    sa.Column('ingredient_type', sa.String(length=50), nullable=True),
    sa.Column('ingredient_quantity', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    # ### end Alembic commands ###
