"""empty message

Revision ID: 4d42dc5a08d6
Revises: 0b61d021e5a0
Create Date: 2019-04-03 20:48:08.729256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d42dc5a08d6'
down_revision = '0b61d021e5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_title', sa.String(length=90), nullable=True),
    sa.Column('recipe_description', sa.String(length=250), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_method', sa.String(length=500), nullable=True),
    sa.Column('recipe_photo', sa.String(), nullable=True),
    sa.Column('recipe_date', sa.String(length=10), nullable=True),
    sa.Column('recipe_rating', sa.Integer(), nullable=True),
    sa.Column('cuisine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], ),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisine.cuisine_id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], ),
    sa.PrimaryKeyConstraint('recipe_id'),
    sa.UniqueConstraint('recipe_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
